### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by pgaxatte** [ovh/terraform-provider-ovh#107]
**This is a macro issue and will be split into different issues for each task.**

We need to do some refactoring and add some guidelines to keep a tidy code:

- [ ] Split types in `types_*.go` matching one or two levels of the route on the API, e.g: `types_dedicated_server.go`, `types_me.go`, ...
- [ ] Make sure the types are named consistently: ResourceName{} when the same struct is used for all HTTP verbs, ResourceNameCreateOpts{} when used only for POST, ResourceNameCreateUpdateOpts{} for POST and PUT, ...
- [ ] Make sure the functions that interact with the API are all consistently named
- [ ] Revamp the `Attributes Reference` in all docs to avoid repeating the arguments above
- [ ] Make sure there are importers everywhere needed

**Comment by pgaxatte** [comment]
I think this is a bit out of date now, I'll just close it
